# Generated by Django 4.2.7 on 2023-11-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("Examinations", "Examinations"),
                            ("Assignments & Projects", "Assignments & Projects"),
                            ("Workshops & Presentations", "Workshops & Presentations"),
                            ("School activities", "School activities"),
                            ("Holidays & Breaks", "Holidays & Breaks"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
